FROM node:16-alpine

# Set the working directory
WORKDIR /app

# copy package.json to work directory, so that we install npm dependencies
COPY package.json /app

# Install app dependencies
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the rest of the app files
COPY . ./app

# Expose the development server port
EXPOSE 3000

# Start the development server
CMD ["yarn", "dev"]